-- ================================================
-- TENUTE — Product image audit + storage bucket
-- ================================================

create table if not exists public.product_image_audit (
  id bigint generated by default as identity primary key,
  product_id text not null,
  sku text,
  name text not null,
  current_url text,
  issue_type text not null check (
    issue_type in (
      'missing_image',
      'missing_gallery',
      'http_error',
      'http_timeout',
      'duplicate_url',
      'small_dimensions',
      'suspicious_domain'
    )
  ),
  http_status integer,
  suggested_url text,
  created_at timestamptz not null default now()
);

create index if not exists product_image_audit_product_id_idx
  on public.product_image_audit (product_id);

create index if not exists product_image_audit_issue_type_idx
  on public.product_image_audit (issue_type);

alter table public.product_image_audit enable row level security;

drop policy if exists "Service role manages product image audit" on public.product_image_audit;
create policy "Service role manages product image audit"
  on public.product_image_audit
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "Admin read product image audit" on public.product_image_audit;
create policy "Admin read product image audit"
  on public.product_image_audit
  for select
  to authenticated
  using ((coalesce(auth.jwt() ->> 'role', '') = 'admin'));

do $$
begin
  if not exists (
    select 1
    from storage.buckets
    where id = 'product-images'
  ) then
    insert into storage.buckets (id, name, public)
    values ('product-images', 'product-images', true);
  end if;
end $$;

